version: 2.1

orbs:
  docker: circleci/docker@2.2.0
  maven: circleci/maven@1.4.1

jobs:
  build-and-push:
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - run:
          name: Extract version
          command: |
            echo "export VERSION=$(mvn -q \
              -Dexec.executable=echo \
              -Dexec.args='${project.version}' \
              --non-recursive \
              exec:exec)" >> $BASH_ENV
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t ghcr.io/${GHCR_USERNAME}/jvm-mode-test:$VERSION .
      - docker/push:
          image: ghcr.io/${GHCR_USERNAME}/jvm-mode-test
          tag: $VERSION
      - run:
          name: Login to GitHub Container Registry
          command: |
            echo "${GHCR_TOKEN}" | docker login ghcr.io -u "${GHCR_USERNAME}" --password-stdin

workflows:
  build_and_push_workflow:
    jobs:
      - build-and-push